### ISSUE TITLE
MaterialProgressBar vertical

### ISSUE THREAD

**Issue by ghost** [glm9637/MaterialWinforms#1]
Hello,

I'm wondering if it is possible use the component MaterialProgressBar vertical?

I tried to create a class that inherites the MaterialProgressBar class, and override CreateParams method, like this: 
`
protected override System.Windows.Forms.CreateParams CreateParams
        {
            get
            {
                System.Windows.Forms.CreateParams cp = base.CreateParams;

```
            cp.Style |= 0x04;

            return cp;
        }
    }
```

`

But isn't work.
What i'm doing wrong?
Regards, 
Weslley

**Comment by glm9637** [comment]
Hi,
I´ve reworked the Progressbar, so now you can set it´s Orientation and the Direction, from which the bar should expand.
Also I´ve added an Indertimate Style, if you need id. 

Regards,
glm9637

**Comment by ghost** [comment]
UOU! Amazing, my friend. 

Thanks a lot!

Regards, 
Weslley
